import { test } from "node:test";
import assert from "node:assert";
import findNumberOfAlternateQuantum from "./findNumberOfAlternateQuantum";

test("findNumberOfAlternateQuantum", () => {
  const input = `.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............`;
  const result = findNumberOfAlternateQuantum(input);
  assert.equal(result, 40);
});
