import { test } from "node:test";
import assert from "node:assert";
import findNumberOfSplits from "./findNumberOfSplits";

test("findNumberOfSplits", () => {
  const input = `.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............`;
  const result = findNumberOfSplits(input);
  assert.equal(result, 21);
});
